const { expectProtectedEndpoint } = require('./routeTestSetup');

describe('Authenticated user routes', () => {
  test.each([
    ['post', '/api/auth/logout'],
    ['post', '/api/auth/logout-all'],
    ['get', '/api/auth/me'],
    ['patch', '/api/auth/change-password'],
    ['patch', '/api/auth/update-profile'],
    ['patch', '/api/auth/update-email'],
    ['patch', '/api/auth/updateemail'],
    ['delete', '/api/auth/delete-account'],
    ['delete', '/api/auth/deleteaccount'],
    ['get', '/api/wallet/'],
    ['get', '/api/wallet/history'],
    ['post', '/api/payment/purchase'],
    ['get', '/api/payment/status/1'],
    ['get', '/api/payment/history'],
    ['post', '/api/paymentmethod/'],
    ['patch', '/api/paymentmethod/1'],
    ['delete', '/api/paymentmethod/1'],
    ['post', '/api/payment-method/'],
    ['patch', '/api/payment-method/1'],
    ['delete', '/api/payment-method/1'],
    ['post', '/api/rating/1'],
    ['get', '/api/rating/1/me'],
    ['delete', '/api/rating/1'],
    ['get', '/api/favorite/'],
    ['post', '/api/favorite/1'],
    ['delete', '/api/favorite/1'],
    ['get', '/api/follow/'],
    ['post', '/api/follow/1'],
    ['delete', '/api/follow/1'],
    ['post', '/api/comment/1'],
    ['patch', '/api/comment/1'],
    ['delete', '/api/comment/1'],
    ['get', '/api/history/'],
    ['get', '/api/notification/'],
    ['patch', '/api/notification/1/read'],
  ])('%s %s requires authentication', expectProtectedEndpoint);
});
